services:
  redis:
    image: redis:7.4.1
    restart: always
    ports:
      - "6379:6379"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - redis-data:/data

volumes:
  redis-data: